name: CI/CD

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".gitignore"
      - "README.md"

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      GUILD_ID: ${{ secrets.GUILD_ID }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
      
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker build and push
      env:
        REPO: twenty_four_bot_test
      run: |
        docker build --build-arg guild_id=$GUILD_ID --build-arg discord_token=$DISCORD_TOKEN . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$REPO:latest
        docker push ${{ secrets.DOCKER_USER }}/$REPO

    - name: Deploy Docker to AWS (EC2)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_KEY }}
        script: |
          docker login
          docker pull ${{ secrets.DOCKER_USER }}/twenty_four_bot_test:latest
          docker stop twenty_four_bot
          docker rm twenty_four_bot
          docker run -t -i -d --rm --name twenty_four_bot ${{ secrets.DOCKER_USER }}/twenty_four_bot_test

        
      
