name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      GUILD_ID: ${{ secrets.GUILD_ID }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.8
      
    - name: Docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker build and push
      env:
        REPO: twenty_four_bot_test
      run: |
        docker build --build-arg GUILD_ID=$GUILD_ID --build-arg DISCORD_TOKEN=$DISCORD_TOKEN . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$REPO:latest
        docker push ${{ secrets.DOCKER_USER }}/$REPO
